# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7825a0d7c5b29e49e504e8d95e5655f69a216d65484e2225a1cc2d466035c57cf237c4866e08f48bf7d32652811f41866af3718811a5706a08f8f75e9e6cb3f3

test:
  secret_key_base: 774a2fb06a6aa51b40a1f5f13e3576302c08d7f15bf39fbea4bc0e981dc0c28e2f4d8814987c2a6cd283313b436c6cb68354a1fdbeefd7a8b5bc55312771ca5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
